---
swagger: "2.0"
info:
  version: "2020-11-28T23:23:44Z"
  title: "dev-star-wars-endpoints"
host: "q2b304ne9k.execute-api.us-east-1.amazonaws.com"
basePath: "/dev"
schemes:
- "https"
paths:
  /api/especies/{id}:
    get:
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        description: ID of species to return
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /api/people:
    get:
      tags:
      - films
      summary: Get all the film resources
      operationId: showFilms
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
    post:
      tags:
      - starships
      summary: Shows all the starships
      description: This can only be done by the logged in user.
      operationId: createUser
      produces:
      - application/json
      - application/xml
      responses:
        default:
          description: successful operation
    
  /api/people/{id}:
    get:
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        description: ID of species to return
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
